# Generated by Django 5.1.6 on 2025-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("failed", "Неудачный платеж"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL для оплаты Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID намерения платежа Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
