version: '3.9'

services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}

  redis:
    image: redis:latest

  web:
    build: .
    command: sh -c "python manage.py test"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env